update

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -2,56 +2,57 @@
   # gcloud compute start-iap-tunnel maric-instance-tp 3000 --local-host-port=localhost:  --zone=us-central1-a
   # $(gcloud info --format="value(basic.python_location)") -m pip install numpy
   # gcloud projects add-iam-policy-binding primeval-mark-378114   --member=user:rakotoarisoaromarickmacdonal@gmail.com --role=roles/iap.tunnelResourceAccessor
-name: Pipeline
+  name: Pipeline
 
-on: 
- push:
-   branches: ['main']
-env:
-  APPLICATION_NAME: flexbox 
-  CONTAINER_NAME: flexdeploy 
-jobs:
-  lint:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-      - run: echo "done"
-  build-image:
-    needs: [lint]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
-
-      - name: login to docker hub
-        uses: docker/login-action@v2
-        with:
-          username: ${{secrets.DOCKERHUB_USERNAME}}
-          password: ${{secrets.DOCKERHUB_PASSWORD}}
-
-      - name: build the docker image
-        uses: docker/build-push-action@v4
-        with:
-          context: .
-          file: ./Dockerfile
-          push: true
-          tags: ${{secrets.DOCKERHUB_USERNAME}}/${{env.APPLICATION_NAME}}:latest
-
-  deploy-on-gcp:
-    needs: [build-image] 
-    name: Deploy to GCP
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3.5.3
-      - name: "Auth" 
-        uses: "google-github-actions/auth@v1"
-        with:
-          credentials_json: "${{ secrets.GCP_SERVICE_ACCT }}"
-      - name: "Bash"
-        shell: 'bash'
-        run: |
-         $(gcloud info --format="value(basic.python_location)") -m pip install numpy --upgrade pip
-         gcloud compute ssh --zone "us-central1-a" "maric-instance-tp" --tunnel-through-iap --project "primeval-mark-378114" --command="docker pull ${{secrets.DOCKERHUB_USERNAME}}/${{env.APPLICATION_NAME}}:latest && docker run -d -p 5000:5000 ${{secrets.DOCKERHUB_USERNAME}}/${{env.APPLICATION_NAME}}:latest"      
+  on: 
+   push:
+     branches: ['main']
+  env:
+    APPLICATION_NAME: flexbox 
+    CONTAINER_NAME: flexdeploy 
+  jobs:
+    lint:
+      runs-on: ubuntu-latest
+      steps:
+        - uses: actions/checkout@v4
+        - run: echo "done"
+    build-image:
+      needs: [lint]
+      runs-on: ubuntu-latest
+      steps:
+        - name: Checkout repository
+          uses: actions/checkout@v4
+  
+        - name: Set up Docker Buildx
+          uses: docker/setup-buildx-action@v2
+  
+        - name: login to docker hub
+          uses: docker/login-action@v2
+          with:
+            username: ${{secrets.DOCKERHUB_USERNAME}}
+            password: ${{secrets.DOCKERHUB_PASSWORD}}
+  
+        - name: build the docker image
+          uses: docker/build-push-action@v4
+          with:
+            context: .
+            file: ./Dockerfile
+            push: true
+            tags: ${{secrets.DOCKERHUB_USERNAME}}/${{env.APPLICATION_NAME}}:flex
+  
+    deploy-on-gcp:
+      needs: [build-image] 
+      name: Deploy to GCP
+      runs-on: ubuntu-latest
+      steps:
+        - uses: actions/checkout@v3.5.3
+        - name: "Auth" 
+          uses: "google-github-actions/auth@v1"
+          with:
+            credentials_json: "${{ secrets.GCP_SERVICE_ACCT }}"
+        - name: "Bash"
+          shell: 'bash'
+          run: |
+           $(gcloud info --format="value(basic.python_location)") -m pip install numpy --upgrade pip
+           gcloud compute ssh --zone "us-central1-a" "maric-instance-tp" --tunnel-through-iap --project "primeval-mark-378114" --command='[ "$(docker ps -qqa -f name=flex)" ] && (echo "Stopping container " && docker stop flex || { echo "Failed to stop container"; exit 1; }) && docker pull ${{secrets.DOCKERHUB_USERNAME}}/${{env.APPLICATION_NAME}}:flex && docker run -d -p 5000:5000 ${{secrets.DOCKERHUB_USERNAME}}/${{env.APPLICATION_NAME}}:flex'      
+  
